# Aliases
# I'll try to only put useful universal aliases here
# Note: this must be in the .bashrc file for thes eto read in correctly.
# if [ -f ~/.bash_aliases ]; then
#     . ~/.bash_aliases
# fi

alias cl='clear && ls'


